Trying to reproduce SI-8556
> test:compile
[info] Compiling 14 Scala sources to /Users/jason/code/slick-pg/core/target/scala-2.10/classes...
[info] Compiling 1 Scala source to /Users/jason/code/slick-pg/addons/spray-json/target/scala-2.10/classes...
[info] Compiling 1 Scala source to /Users/jason/code/slick-pg/addons/jts/target/scala-2.10/classes...
[info] Compiling 1 Scala source to /Users/jason/code/slick-pg/addons/json4s/target/scala-2.10/classes...
[info] Compiling 1 Scala source to /Users/jason/code/slick-pg/addons/play-json/target/scala-2.10/classes...
[info] Compiling 1 Scala source to /Users/jason/code/slick-pg/addons/joda-time/target/scala-2.10/classes...
[info] Compiling 1 Scala source to /Users/jason/code/slick-pg/addons/threeten/target/scala-2.10/classes...
[info] Compiling 1 Scala source to /Users/jason/code/slick-pg/addons/date2/target/scala-2.10/classes...
[info] Compiling 8 Scala sources to /Users/jason/code/slick-pg/target/scala-2.10/classes...
[info] Compiling 1 Scala source to /Users/jason/code/slick-pg/core/target/scala-2.10/test-classes...
[info] Compiling 2 Scala sources to /Users/jason/code/slick-pg/addons/play-json/target/scala-2.10/test-classes...
[info] Compiling 2 Scala sources to /Users/jason/code/slick-pg/addons/json4s/target/scala-2.10/test-classes...
[info] Compiling 2 Scala sources to /Users/jason/code/slick-pg/addons/date2/target/scala-2.10/test-classes...
[info] Compiling 2 Scala sources to /Users/jason/code/slick-pg/addons/joda-time/target/scala-2.10/test-classes...
[info] Compiling 2 Scala sources to /Users/jason/code/slick-pg/addons/threeten/target/scala-2.10/test-classes...
[info] Compiling 2 Scala sources to /Users/jason/code/slick-pg/addons/jts/target/scala-2.10/test-classes...
[info] Compiling 2 Scala sources to /Users/jason/code/slick-pg/addons/spray-json/target/scala-2.10/test-classes...
[info] Compiling 9 Scala sources to /Users/jason/code/slick-pg/target/scala-2.10/test-classes...
[error] /Users/jason/code/slick-pg/src/test/scala/com/github/tminglei/slickpg/PgAggFunctionTest.scala:36: value forDistinct is not a member of com.github.tminglei.slickpg.MyPostgresDriver.simple.PgAggregateFunctions.StringAgg
[error]       val q = tabs.map(t => (t.name ^: StringAgg(",").forDistinct().orderBy(t.name), t.count ^: Avg[Int]))
[error]                                                       ^
[error] /Users/jason/code/slick-pg/src/test/scala/com/github/tminglei/slickpg/PgAggFunctionTest.scala:36: value ^: is not a member of com.github.tminglei.slickpg.MyPostgresDriver.simple.PgAggregateFunctions.Avg[Int]
[error]       val q = tabs.map(t => (t.name ^: StringAgg(",").forDistinct().orderBy(t.name), t.count ^: Avg[Int]))
[error]                                                                                              ^
[error] /Users/jason/code/slick-pg/src/test/scala/com/github/tminglei/slickpg/PgAggFunctionTest.scala:36: type mismatch;
[error]  found   : scala.slick.lifted.Shape[Nothing,scala.slick.lifted.ConstColumn[Nothing],Nothing,scala.slick.lifted.ConstColumn[Nothing]]
[error]  required: scala.slick.lifted.Shape[_ <: scala.slick.lifted.FlatShapeLevel, Nothing, T, scala.slick.lifted.ConstColumn[Nothing]]
[error] Note: Nothing <: scala.slick.lifted.FlatShapeLevel, but class Shape is invariant in type Level.
[error] You may wish to investigate a wildcard type such as `_ <: scala.slick.lifted.FlatShapeLevel`. (SLS 3.2.10)
[error] Note: Nothing <: T, but class Shape is invariant in type Unpacked_.
[error] You may wish to investigate a wildcard type such as `_ <: T`. (SLS 3.2.10)
[error]       val q = tabs.map(t => (t.name ^: StringAgg(",").forDistinct().orderBy(t.name), t.count ^: Avg[Int]))
[error]                       ^
[error] /Users/jason/code/slick-pg/src/test/scala/com/github/tminglei/slickpg/PgAggFunctionTest.scala:37: No matching Shape found.
[error] Slick does not know how to map the given types.
[error] Possible causes: T in Table[T] does not match your * projection. Or you use an unsupported type in a Query (e.g. scala List).
[error]   Required level: scala.slick.lifted.FlatShapeLevel
[error]      Source type: scala.slick.lifted.Query[scala.slick.lifted.ConstColumn[Nothing],Nothing,[+A]Seq[A]]
[error]    Unpacked type: U
[error]      Packed type: Any
[error]       println(s"q = ${q.selectStatement}")
[error]                         ^
[error] /Users/jason/code/slick-pg/src/test/scala/com/github/tminglei/slickpg/PgAggFunctionTest.scala:38: value first is not a member of scala.slick.lifted.Query[scala.slick.lifted.ConstColumn[Nothing],Nothing,Seq]
[error]       assertEquals(("bar,foo,quux", 4), q.first)
[error]                                           ^
[error] /Users/jason/code/slick-pg/src/test/scala/com/github/tminglei/slickpg/PgAggFunctionTest.scala:40: value ^: is not a member of com.github.tminglei.slickpg.MyPostgresDriver.simple.PgAggregateFunctions.Corr
[error]       val q1 = tabs.map(t => (t.y, t.x) ^: Corr())
[error]                                         ^
[error] /Users/jason/code/slick-pg/src/test/scala/com/github/tminglei/slickpg/PgAggFunctionTest.scala:40: type mismatch;
[error]  found   : scala.slick.lifted.Shape[Nothing,scala.slick.lifted.ConstColumn[Nothing],Nothing,scala.slick.lifted.ConstColumn[Nothing]]
[error]  required: scala.slick.lifted.Shape[_ <: scala.slick.lifted.FlatShapeLevel, Nothing, T, scala.slick.lifted.ConstColumn[Nothing]]
[error] Note: Nothing <: scala.slick.lifted.FlatShapeLevel, but class Shape is invariant in type Level.
[error] You may wish to investigate a wildcard type such as `_ <: scala.slick.lifted.FlatShapeLevel`. (SLS 3.2.10)
[error] Note: Nothing <: T, but class Shape is invariant in type Unpacked_.
[error] You may wish to investigate a wildcard type such as `_ <: T`. (SLS 3.2.10)
[error]       val q1 = tabs.map(t => (t.y, t.x) ^: Corr())
[error]                        ^
[error] /Users/jason/code/slick-pg/src/test/scala/com/github/tminglei/slickpg/PgAggFunctionTest.scala:41: No matching Shape found.
[error] Slick does not know how to map the given types.
[error] Possible causes: T in Table[T] does not match your * projection. Or you use an unsupported type in a Query (e.g. scala List).
[error]   Required level: scala.slick.lifted.FlatShapeLevel
[error]      Source type: scala.slick.lifted.Query[scala.slick.lifted.ConstColumn[Nothing],Nothing,[+A]Seq[A]]
[error]    Unpacked type: U
[error]      Packed type: Any
[error]       println(s"q = ${q1.selectStatement}")
[error]                          ^
[error] /Users/jason/code/slick-pg/src/test/scala/com/github/tminglei/slickpg/PgAggFunctionTest.scala:42: value first is not a member of scala.slick.lifted.Query[scala.slick.lifted.ConstColumn[Nothing],Nothing,Seq]
[error]       assertEquals(0.45, q1.first, 0.01)
[error]                             ^
[error] 9 errors found
[error] (slick-pg/test:compile) Compilation failed
[error] Total time: 29 s, completed May 1, 2014 2:57:09 PM